name: Build Desktop App

on:
  workflow_dispatch:   # you can run it manually from Actions tab
  push:
    branches:
      - main           # or your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed run.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: GmailDesktopApp
        path: dist/run.exe
